[project]
name = "xplique-adapters"
version = "0.1.0"
description = "Adapters and extension modules for Xplique, for model-specific explainability."
readme = "README.md"
requires-python = ">=3.10,<3.14"
license = { file = "LICENSE" }
authors = [
  { name = "DEEL Core Team ", email = "agustin-martin.picard@irt-saintexupery.com"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]
dependencies = [
  "xplique>=2.0.0",
  "keras-cv",
  "deprecated>=1.1.0",
  "einops>=0.1.0",
  "matplotlib>=1.4.3",
  "numpy>=2.0.0",
  "opencv-python>=3.4.11.39",
  "ruff>=0.15.0",
  "scikit-image>=0.14.1,<=0.25.2",
  "scikit-learn>=0.14.1,<=1.7.2",
  "scipy>=1.0.0,<=1.15.3",
  "tensorflow[and-cuda]>=2.16.1,<=2.20.0",
  "tensorflow-probability[tf]>=0.20.1,<=0.25.0",
]

[dependency-groups]
dev = [
    "bump2version",
    "docutils",
    "markdown",
    "mkdocs",
    "mkdocs-material",
    "mypy",
    "mypy-extensions",
    "numkdoc",
    "pre-commit",
    "pygments",
    "ruff",
    "pymdown-extensions",
    "pytest",
    "pytest-cov",
    "tox",
    "tox-uv",
]
torch = [
  "torch>=2.5.0,<=2.10.0",
  "torchvision>=0.23.0",
]
yolo = [
  "ultralytics",
  "overcomplete>=0.2.8",
]

[tool.setuptools.packages.find]
include = ["xplique_adapters*"]

[tool.bumpversion]
current_version = "0.1.0"
commit = true
tag = false

[[tool.bumpversion.files]]
filename = "pyproject.toml"

[[tool.bumpversion.files]]
filename = "xplique_adapters/__init__.py"
